# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoClass' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CULColorPicker'
  pod 'SwiftSVG', '~> 2.0'
  
  # Pods for DemoClass
  target 'DemoClassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoClassUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
